apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      run: nginx-deployment
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-deployment
    spec:
      containers:
      - name: nginx-custom
        image: capeguy/task_a:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
